program: src/dcase2026_task1/experiments/training.py
project: dcase2026-task1
method: bayes
metric:
  name: val/hierarchical_f1
  goal: maximize

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: !!float 1e-6
    max: !!float 9e-6
  weight_decay:
    value: 0.0
  warmup_epochs:
    value: 1
  lr_decay_start_epoch:
    value: 2
  min_learning_rate:
    value: !!float 1e-7
  max_epochs:
    value: 30
  batch-size:
    value: 32


command:
  - ${env}
  - ${interpreter}
  - -m
  - dcase2026_task1.experiments.training
  - --wandb-project=dcase2026-task1
  - --wandb-mode=online
  - --embedding-model=clap
  - ${args}
